kind: CronJob
apiVersion: batch/v1
metadata:
  name: test-1
  labels:
    app: test-1
    app.kubernetes.io/component: test-1
    app.kubernetes.io/instance: test-1
    app.kubernetes.io/name: test-1
    app.kubernetes.io/part-of: opbeans-java-app
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: 'curlimages/curl:7.87.0'
              args:
                - '--insecure'
                - '--location'
                - '-v'
                - >-
                  https://.../dashboard
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

---

kind: CronJob
apiVersion: batch/v1
metadata:
  name: test-2
  labels:
    app: test-2
    app.kubernetes.io/component: test-2
    app.kubernetes.io/instance: test-2
    app.kubernetes.io/name: test-2
    app.kubernetes.io/part-of: opbeans-java-app
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: 'curlimages/curl:7.87.0'
              args:
                - '--insecure'
                - '--location'
                - '-v'
                - >-
                  https://.../products
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

---

kind: CronJob
apiVersion: batch/v1
metadata:
  name: test-3
  labels:
    app: test-3
    app.kubernetes.io/component: test-3
    app.kubernetes.io/instance: test-3
    app.kubernetes.io/name: test-3
    app.kubernetes.io/part-of: opbeans-java-app
spec:
  schedule: '*/15 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: 'curlimages/curl:7.87.0'
              args:
                - '--insecure'
                - '--location'
                - '-v'
                - >-
                  https://.../is-it-coffee-time
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
